export const GET_EXPEIIENCE_REQUEST = "GET_EXPEIIENCE_REQUEST";
export const GET_EXPEIIENCE_SUCCESS = "GET_EXPEIIENCE_SUCCESS";
export const GET_EXPEIIENCE_FAIL = "GET_EXPEIIENCE_FACONTACT";

export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAIL = "GET_PROJECT_FACONTACT";

export const GET_CONTACT_REQUEST = "GET_CONTACT_REQUEST";
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAIL = "GET_CONTACT_FACONTACT";