export const USER_CONTACT_REQUEST = "USER_CONTACT_REQUEST";
export const USER_CONTACT_SUCCESS = "USER_CONTACT_SUCCESS";
export const USER_CONTACT_FAIL = "USER_CONTACT_FACONTACT";

export const USER_Login_REQUEST = "USER_Login_REQUEST";
export const USER_Login_SUCCESS = "USER_Login_SUCCESS";
export const USER_Login_FAIL = "USER_Login_FACOLogin"
export const USER_LOGOUT = "USER_LOGOUT";

export const LOGOUT_DELETE_REQUEST = "LOGOUT_DELETE_REQUEST";
export const LOGOUT_DELETE_SUCCESS = "LOGOUT_DELETE_SUCCESS";
export const LOGOUT_DELETE_FAIL = "LOGOUT_DELETE_FAIL";

export const USER_EXPEIIENCE_REQUEST = "USER_EXPEIIENCE_REQUEST";
export const USER_EXPEIIENCE_SUCCESS = "USER_EXPEIIENCE_SUCCESS";
export const USER_EXPEIIENCE_FAIL = "USER_EXPEIIENCE_FACONTACT";

export const USER_PROJECT_REQUEST = "USER_PROJECT_REQUEST";
export const USER_PROJECT_SUCCESS = "USER_PROJECT_SUCCESS";
export const USER_PROJECT_FAIL = "USER_PROJECT_FACONTACT";

